# Generated by Django 4.2.1 on 2023-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='Pin_img',
            field=models.ImageField(upload_to='PINS'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_photos'),
        ),
    ]
